export const holdingColumns = ["Script", "Exchange", "Quantity", "Current Price", "Current Value", "% Change"];
export const ledgerExcelColumns = ["Voucher Date", "Voucher Number", "Narration", "Debit/ Credit", "Amount ₹"];
export const ledgerPdfColumns = ["Voucher Date", "Voucher Number", "Narration", "Debit/ Credit", "Amount"];
export const marginExcelColumns = ["Adjusted Ledger Balance ₹", "Gross Holding Value ₹", "Gross Margin ₹", "Available Margin ₹"];
export const marginPdfColumns = ["Adjusted Ledger Balance", "Gross Holding Value", "Gross Margin", "Available Margin"];
export const orderBookExcelColumns = ["Remote Order ID", "Exchange", "Buy/ Sell", "Exchange Order Time", "Script", "Quantity", "Rate ₹", "Order Status", "Market/ Limit"];
export const orderBookPdfColumns = ["Remote Order ID", "Exchange", "Buy/ Sell", "Exchange Order Time", "Script", "Quantity", "Rate", "Order Status", "Market/ Limit"];
export const tradeBookExcelColumns = ["Remote Order ID", "Exchange", "Buy/ Sell", "Exchange Trade Time", "Script", "Quantity", "Rate ₹"];
export const tradeBookPdfColumns = ["Remote Order ID", "Exchange", "Buy/ Sell", "Exchange Trade Time", "Script", "Quantity", "Rate"];